/**
 * One-shot provisioning script.
 *
 * Generates two fresh BIP-39 mnemonics (Alice + Bob), derives all
 * five asset addresses for each, registers both with the production
 * backend (so the `is_returning_user` bypass kicks in on every
 * subsequent smoke run), and writes the mnemonics to a local file
 * that is gitignored.
 *
 * Run once on the operator's laptop:
 *
 *   npm run provision -w @smirk/smoke-tests
 *
 * Outputs:
 *   - stdout: address list to fund
 *   - packages/smoke-tests/secrets/smoke-mnemonics.env: env-shaped
 *     file ready to scp to /etc/smirk-smoke.env on the tipbot server.
 *
 * Idempotent in the sense that re-running generates NEW wallets —
 * which is usually NOT what you want, so refuse to overwrite an
 * existing secrets file unless `--force` is passed.
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SmirkApi, bootstrapAuth, generateMnemonicPhrase } from '@smirk/core';

import { unlockedWalletFromMnemonic } from './lib/wallet.js';

const BACKEND_URL = process.env.SMOKE_BACKEND_URL ?? 'https://backend.smirk.cash';

const __filename = fileURLToPath(import.meta.url);
const SECRETS_DIR = join(dirname(__filename), '..', 'secrets');
const SECRETS_FILE = join(SECRETS_DIR, 'smoke-mnemonics.env');

const force = process.argv.includes('--force');

async function provisionOne(label: string) {
  const mnemonic = generateMnemonicPhrase();
  const wallet = unlockedWalletFromMnemonic(mnemonic);
  const api = new SmirkApi(BACKEND_URL);

  console.log(`\n${label}:`);
  console.log(`  BTC   ${wallet.addresses.btc}`);
  console.log(`  LTC   ${wallet.addresses.ltc}`);
  console.log(`  XMR   ${wallet.addresses.xmr}`);
  console.log(`  WOW   ${wallet.addresses.wow}`);
  console.log(`  GRIN  ${wallet.addresses.grin}`);
  console.log(`  fingerprint: ${wallet.fingerprint}`);

  // Register against prod. Fresh wallet — PoW solve runs (~3s on a
  // fast laptop). Subsequent smoke runs hit the is_returning_user
  // bypass.
  console.log(`  registering with ${BACKEND_URL} (PoW solve ~3s)...`);
  try {
    const result = await bootstrapAuth(api, wallet);
    console.log(`  ✓ registered as user_id ${result.userId.slice(0, 8)}…`);
  } catch (e) {
    console.log(`  ✗ registration failed: ${e instanceof Error ? e.message : String(e)}`);
    console.log(`    (mnemonic is still valid — re-run smoke later to register)`);
  }

  return { mnemonic, addresses: wallet.addresses, fingerprint: wallet.fingerprint };
}

async function main() {
  if (existsSync(SECRETS_FILE) && !force) {
    console.error(
      `ERROR: ${SECRETS_FILE} already exists.\n` +
        `Re-running would generate NEW wallets — existing test wallets + any funds on them would be orphaned.\n` +
        `If you really want to re-provision, pass --force (and back up the existing file first).`,
    );
    process.exit(1);
  }

  console.log(`Provisioning two smoke-test wallets against ${BACKEND_URL}`);
  console.log(`Secrets will be written to: ${SECRETS_FILE}`);

  const alice = await provisionOne('ALICE');
  const bob = await provisionOne('BOB');

  mkdirSync(SECRETS_DIR, { recursive: true });
  // chmod 600 — secrets-style file. Caller is expected to scp to
  // /etc/smirk-smoke.env on the tipbot server with the same perms.
  const body =
    `# Generated by packages/smoke-tests/src/provision.ts on ${new Date().toISOString()}\n` +
    `# DO NOT COMMIT. Copy to /etc/smirk-smoke.env on the tipbot server with chmod 600.\n` +
    `\n` +
    `SMOKE_BACKEND_URL=${BACKEND_URL}\n` +
    `SMOKE_ALICE_MNEMONIC="${alice.mnemonic}"\n` +
    `SMOKE_BOB_MNEMONIC="${bob.mnemonic}"\n` +
    `# Set after creating the Discord webhook:\n` +
    `# SMOKE_DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/...\n`;
  writeFileSync(SECRETS_FILE, body, { mode: 0o600 });
  console.log(`\n✓ wrote ${SECRETS_FILE}`);

  console.log(`\n--- FUND THESE ADDRESSES ---`);
  console.log(`Send ~$5-10 to each (smaller is fine; phase 1 scenarios don't move funds yet).`);
  console.log(`\nALICE:`);
  console.log(`  BTC   ${alice.addresses.btc}`);
  console.log(`  LTC   ${alice.addresses.ltc}`);
  console.log(`  XMR   ${alice.addresses.xmr}`);
  console.log(`  WOW   ${alice.addresses.wow}`);
  console.log(`  GRIN  ${alice.addresses.grin}`);
  console.log(`\nBOB:`);
  console.log(`  BTC   ${bob.addresses.btc}`);
  console.log(`  LTC   ${bob.addresses.ltc}`);
  console.log(`  XMR   ${bob.addresses.xmr}`);
  console.log(`  WOW   ${bob.addresses.wow}`);
  console.log(`  GRIN  ${bob.addresses.grin}`);
  console.log(`\nNext: scp ${SECRETS_FILE} to /etc/smirk-smoke.env on the tipbot server (see README).`);
}

main().catch((e) => {
  console.error('provision crashed:', e);
  process.exit(1);
});
